include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - always_specify_types
    - prefer_final_locals
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_const_declarations
    - unnecessary_this
    - prefer_single_quotes
    - avoid_unused_constructor_parameters
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - prefer_relative_imports
    - avoid_redundant_argument_values
    - avoid_void_async
    - unnecessary_lambdas

formatter:
  page_width: 300
